plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = '1.0.0'
group = 'dev.backrooms'
base { archivesName = 'backrooms' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods { backrooms { source sourceSets.main } }
        }
        client {}
        server { args '--nogui' }
    }
}

repositories { mavenCentral() }
dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.named('test') {
    useJUnitPlatform()
    maxHeapSize = '128m'
}
tasks.named('jar') {
    manifest.attributes('Implementation-Version': project.version)
    finalizedBy 'reobfJar'
}
